# Layton
# WARN: DIDN'T SET WORLD COORDINATES



def outline(t):
    t.pendown()
    t.right(10)
    t.forward(80)
    t.left(120)
    t.forward(80)
    t.right(20)
    t.forward(80)
    t.right(30)
    t.forward(40)
    t.right(60)
    t.forward(45)
    t.right(120)
    t.forward(40)
    t.right(60)
    t.forward(41)
    t.penup()
    t.home()
    t.pendown()
    t.left(190)
    t.forward(80)
    t.right(120)
    t.forward(80)
    t.left(20)
    t.forward(80)
    t.left(30)
    t.forward(40)
    t.left(60)
    t.forward(45)
    t.left(120)
    t.forward(40)
    t.left(60)
    t.forward(41)
    t.penup()

def nose(t):
    t.home()
    t.right(10)
    t.forward(80)
    t.pendown()
    t.right(80)
    t.forward(80)
    t.right(100)
    t.forward(80)
    t.left(20)
    t.forward(80)
    t.right(100)
    t.forward(80)
    t.left(180)
    t.forward(80)
    t.left(90)
    t.penup()


def chin(t):
    t.forward(15)
    t.right(20)
    t.pendown()
    t.right(40)
    t.forward(20)
    t.left(50)
    t.forward(55)
    t.left(20)
    t.forward(55)
    t.left(50)
    t.forward(20)
    t.penup()

def nostril(t):
    t.left(30)
    t.forward(45)
    t.left(90)
    t.forward(20)
    t.left(15)
    t.pendown()
    t.forward(12)
    t.penup()
    t.right(15)
    t.forward(65)
    t.right(15)
    t.pendown()
    t.forward(12)
    t.penup()

def head(t):
    t.forward(40)
    t.pendown()
    t.right(55)
    t.forward(230)
    t.right(50)
    t.forward(90)
    t.right(40)
    t.forward(125)
    t.right(40)
    t.forward(125)
    t.right(45)
    t.forward(90)
    t.right(44)
    t.forward(230)
    t.penup()

def righthorn(t):
    t.left(180)
    t.forward(235)
    t.left(20)
    t.right(90)
    t.pendown()
    t.forward(15)
    t.right(35)
    t.forward(30) 
    t.left(50)   
    t.forward(50)
    t.left(130)
    t.forward(55)
    t.left(50)
    t.forward(35)
    t.right(30)
    t.forward(22)
    t.penup()

def rightear(t):
    t.right(40)
    t.forward(15)
    t.right(100)
    t.pendown()
    t.forward(40)
    t.left(35)
    t.forward(35)
    t.left(125)
    t.forward(75)
    t.penup()


def leftear(t):
    t.right(5)
    t.forward(235)
    t.right(55)
    t.forward(10)
    t.pendown()
    t.left(50)
    t.backward(10)
    t.forward(75)
    t.left(130)
    t.forward(35)
    t.left(30)
    t.forward(38)
    t.penup()

def lefthorn(t):
    t.right(90)
    t.forward(15)
    t.right(90)
    t.forward(5)
    t.left(40)
    t.pendown()
    t.forward(22)
    t.right(35)
    t.forward(35)
    t.left(65)
    t.forward(45)
    t.left(110)
    t.forward(40)
    t.left(60)
    t.forward(22)
    t.right(25)
    t.forward(15)
    t.penup()

def draw_cow(t):
    outline(t)
    nose(t)
    chin(t)
    nostril(t)
    head(t)
    righthorn(t)
    rightear(t)
    leftear(t)
    lefthorn(t)