# Layton
# WARN: DIDN'T SET WORLD COORDINATES

import turtle

def outline():
    turtle.pendown()
    turtle.right(10)
    turtle.forward(80)
    turtle.left(120)
    turtle.forward(80)
    turtle.right(20)
    turtle.forward(80)
    turtle.right(30)
    turtle.forward(40)
    turtle.right(60)
    turtle.forward(45)
    turtle.right(120)
    turtle.forward(40)
    turtle.right(60)
    turtle.forward(41)
    turtle.penup()
    turtle.home()
    turtle.pendown()
    turtle.left(190)
    turtle.forward(80)
    turtle.right(120)
    turtle.forward(80)
    turtle.left(20)
    turtle.forward(80)
    turtle.left(30)
    turtle.forward(40)
    turtle.left(60)
    turtle.forward(45)
    turtle.left(120)
    turtle.forward(40)
    turtle.left(60)
    turtle.forward(41)
    turtle.penup()

def nose():
    turtle.home()
    turtle.right(10)
    turtle.forward(80)
    turtle.pendown()
    turtle.right(80)
    turtle.forward(80)
    turtle.right(100)
    turtle.forward(80)
    turtle.left(20)
    turtle.forward(80)
    turtle.right(100)
    turtle.forward(80)
    turtle.left(180)
    turtle.forward(80)
    turtle.left(90)
    turtle.penup()


def chin():
    turtle.forward(15)
    turtle.right(20)
    turtle.pendown()
    turtle.right(40)
    turtle.forward(20)
    turtle.left(50)
    turtle.forward(55)
    turtle.left(20)
    turtle.forward(55)
    turtle.left(50)
    turtle.forward(20)
    turtle.penup()

def nostril():
    turtle.left(30)
    turtle.forward(45)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(15)
    turtle.pendown()
    turtle.forward(12)
    turtle.penup()
    turtle.right(15)
    turtle.forward(65)
    turtle.right(15)
    turtle.pendown()
    turtle.forward(12)
    turtle.penup()

def head():
    turtle.forward(40)
    turtle.pendown()
    turtle.right(55)
    turtle.forward(230)
    turtle.right(50)
    turtle.forward(90)
    turtle.right(40)
    turtle.forward(125)
    turtle.right(40)
    turtle.forward(125)
    turtle.right(45)
    turtle.forward(90)
    turtle.right(44)
    turtle.forward(230)
    turtle.penup()

def righthorn():
    turtle.left(180)
    turtle.forward(235)
    turtle.left(20)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(15)
    turtle.right(35)
    turtle.forward(30) 
    turtle.left(50)   
    turtle.forward(50)
    turtle.left(130)
    turtle.forward(55)
    turtle.left(50)
    turtle.forward(35)
    turtle.right(30)
    turtle.forward(22)
    turtle.penup()

def rightear():
    turtle.right(40)
    turtle.forward(15)
    turtle.right(100)
    turtle.pendown()
    turtle.forward(40)
    turtle.left(35)
    turtle.forward(35)
    turtle.left(125)
    turtle.forward(75)
    turtle.penup()


def leftear():
    turtle.right(5)
    turtle.forward(235)
    turtle.right(55)
    turtle.forward(10)
    turtle.pendown()
    turtle.left(50)
    turtle.backward(10)
    turtle.forward(75)
    turtle.left(130)
    turtle.forward(35)
    turtle.left(30)
    turtle.forward(38)
    turtle.penup()

def lefthorn():
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(5)
    turtle.left(40)
    turtle.pendown()
    turtle.forward(22)
    turtle.right(35)
    turtle.forward(35)
    turtle.left(65)
    turtle.forward(45)
    turtle.left(110)
    turtle.forward(40)
    turtle.left(60)
    turtle.forward(22)
    turtle.right(25)
    turtle.forward(15)
    turtle.penup()

def draw_cow():
    outline()
    nose()
    chin()
    nostril()
    head()
    righthorn()
    rightear()
    leftear()
    lefthorn()