

def drawHeadL(turtle):
    # head
    turtle.right(90)
    turtle.forward(350)
    turtle.right(90)
    turtle.pendown()
    turtle.forward(68)
    turtle.right(87)
    turtle.forward(120)
    turtle.left(7)
    turtle.forward(162)
    turtle.left(50)
    turtle.forward(68)
    turtle.right(73)
    turtle.forward(83)
    turtle.left(49)
    turtle.forward(67)
    turtle.right(49)
    turtle.forward(162)
    turtle.back(60)
    turtle.left(67)
    turtle.forward(80)
def drawEarL(turtle):
    turtle.penup()
    turtle.left(140)
    turtle.forward(272)
    turtle.pendown()
    turtle.right(75)
    turtle.forward(50)
    turtle.right(78)
    turtle.forward(322)
    turtle.right(79)
    turtle.forward(158)
    turtle.right(45)
    turtle.forward(229)
    turtle.right(95)
    turtle.forward(45)
    turtle.left(113)
    turtle.forward(51)
    turtle.right(50)
    turtle.forward(45)
    turtle.penup()
def drawTuskL(turtle):
    turtle.penup()
    turtle.home()
    turtle.right(90)
    turtle.forward(350)
    turtle.right(90)
    turtle.forward(68)
    turtle.right(87)
    turtle.forward(120)
    turtle.left(7)
    turtle.forward(162)
    turtle.pendown()
    turtle.left(160)
    turtle.forward(98)
    turtle.left(18)
    turtle.forward(175)
    turtle.right(160)
    turtle.forward(182)
    turtle.right(36)
    turtle.forward(144)
    turtle.right(113)
    turtle.forward(70)
    turtle.penup()

    # eyes
def drawHeadR(turtle):
    # head
   turtle.right(90)
   turtle.forward(350)
   turtle.right(90)
   turtle.pendown()
   turtle.forward(5)
   turtle.left(180)
   turtle.forward(5)
   turtle.forward(68)
   turtle.left(87)
   turtle.forward(120)
   turtle.right(7)
   turtle.forward(162)
   turtle.right(50)
   turtle.forward(68)
   turtle.left(73)
   turtle.forward(83)
   turtle.right(49)
   turtle.forward(67)
   turtle.left(49)
   turtle.forward(162)
   turtle.back(60)
   turtle.right(67)
   turtle.forward(80)
def drawEarR(turtle):
    turtle.penup()
    turtle.right(140)
    turtle.forward(272)
    turtle.pendown()
    turtle.left(75)
    turtle.forward(50)
    turtle.left(78)
    turtle.forward(322)
    turtle.left(79)
    turtle.forward(158)
    turtle.left(45)
    turtle.forward(229)
    turtle.left(95)
    turtle.forward(45)
    turtle.right(113)
    turtle.forward(51)
    turtle.left(50)
    turtle.forward(45)
    turtle.penup()
def drawTuskR(turtle):
    turtle.penup()
    turtle.home()
    turtle.right(90)
    turtle.forward(350)
    turtle.left(90)
    turtle.forward(68)
    turtle.left(87)
    turtle.forward(120)
    turtle.right(7)
    turtle.forward(162)
    turtle.pendown()
    turtle.right(160)
    turtle.forward(98)
    turtle.right(18)
    turtle.forward(175)
    turtle.left(160)
    turtle.forward(182)
    turtle.left(36)
    turtle.forward(144)
    turtle.left(113)
    turtle.forward(70)
    turtle.penup()

    # eyes

def draw_elephant(turtle):
    drawHeadL(turtle)
    drawEarL(turtle)
    drawTuskL(turtle)
    turtle.home()
    drawHeadR(turtle)
    drawEarR(turtle)
    drawTuskR(turtle)


